# Generated by Django 3.2.9 on 2021-11-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211125_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='location',
        ),
    ]
