# Generated by Django 3.2.9 on 2021-12-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211125_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.location'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.location'),
        ),
    ]
