# Generated by Django 3.2.9 on 2021-12-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_create',
            new_name='date',
        ),
    ]
