# Generated by Django 3.2.9 on 2021-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ManyToManyField(to='order.OrderItem'),
        ),
    ]
