# Generated by Django 3.2.9 on 2021-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_date_create_orderitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
