# Generated by Django 3.2.9 on 2021-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211125_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creat order'), ('ACCEPT', 'Accept order'), ('INPROGREES', 'In progress order'), ('FINISHED', 'Finished order')], default='CREATED', max_length=25),
        ),
    ]
