# Generated by Django 3.2.9 on 2021-11-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='order.supplier'),
        ),
    ]
