# Generated by Django 3.2.9 on 2021-12-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211211_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['date_create'], 'verbose_name_plural': 'Order Status'},
        ),
    ]
